spring:
  webflux:
    base-path: /recipes
  application:
    name: recipe
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
    redis:
      repositories:
        enabled: false

server:
  port: 8030

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

external-service-url:
  member: ${MEMBER_SERVICE_URL}

resilience4j:
  circuitbreaker:
    instances:
      member-service:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - shop.tsrecipe.recipe.exception.BaseException

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  bucketName: ${AWS_S3_BUCKET_NAME}