spring:
  application:
    name: recipe
  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      repositories:
        enabled: false

server:
  port: 8030

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

external-service-url:
  member: "http://localhost:8020"