spring:
  webflux:
    base-path: /recipes
  application:
    name: recipe
  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      repositories:
        enabled: false

server:
  port: 8030

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

external-service-url:
  member: "http://member"