apiVersion: v1
kind: Secret
metadata:
  name: recipe-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: "__PROFILE__"
  MONGO_URL: "__JMONGO_URL__"
  AWS_ACCESS_KEY: "__AWS_ACCESS_KEY__"
  AWS_SECRET_KEY: "__AWS_SECRET_KEY__"
  AWS_REGION: "__AWS_REGION__"
  AWS_S3_BUCKET_NAME: "__AWS_S3_BUCKET_NAME__"