name: Build and Deploy Recipe

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAG="prod"
          else
            TAG="dev"
          fi
          echo "Using tag: $TAG"

          docker build \
          --build-arg PROFILE=$TAG \
          --build-arg MONGO_URL=${{ secrets.MONGO_URL }} \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_RECIPE }}:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_REPO_RECIPE }}:$TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Kubernetes rollout restart
        env:
          KUBECONFIG_PATH: ./kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $KUBECONFIG_PATH
          chmod 600 $KUBECONFIG_PATH
          kubectl --kubeconfig=$KUBECONFIG_PATH rollout restart deployment/${{ vars.DOCKER_REPO_RECIPE }}
          kubectl --kubeconfig=$KUBECONFIG_PATH rollout status deployment/${{ vars.DOCKER_REPO_RECIPE }}